### ISSUE TITLE
Makerbot: Bigger print sending fails

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/print3d#6]
Sending bigger prints to the WiFi box when a makerbot is connected fails. The sendPrintPart request times out. At sendIndez 12000/51046 for example. The rest of the api still responds. Maybe appending the gcode takes more and more time?

**Comment by woutgg** [comment]
Two reasons why this might be fixed now:
- In the print3d improvements, the makerbot driver also uses GCodeBuffer which should make it more stable.
- GCode to S3G conversion is now done on the fly (just before the data is sent to the printer) instead of as soon as it is appended, which was the original approach.

**Comment by olijf** [comment]
So is this still an issue? Can we maybe close this one?

**Comment by peteruithoven** [comment]
Depends on the results of the test Jeroen is doing, I'll put it in the 0.10.10 milestone.

**Comment by peteruithoven** [comment]
For the release of the 0.10.10 we've done lot's of tests. I'm closing this issue for now.
